#!/usr/bin/env bash
# Generate the production .env for claude-team-usage and scp it to the
# ConoHa app env file. Run interactively in iTerm/Terminal — Claude Code's
# `!` bash does not have a TTY and will break on `read -s` prompts.
set -euo pipefail

CATEGORY="app"
APP_NAME="claude-team-usage"
SERVER_USER="deploy"
SERVER_HOST_ALIAS="conoha-deploy" # uses ~/.ssh/config alias
REMOTE_ENV="/var/www/_shared/apps/${CATEGORY}-${APP_NAME}.env"
APP_URL="https://app.instyle.group/${APP_NAME}"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }

if ! command -v ssh >/dev/null 2>&1; then
  echo "ssh not found" >&2; exit 1
fi
if ! ssh -o BatchMode=yes -o ConnectTimeout=5 "${SERVER_HOST_ALIAS}" 'true' 2>/dev/null; then
  echo "Cannot reach ${SERVER_HOST_ALIAS} via ~/.ssh/config. Configure the alias first." >&2
  exit 1
fi

bold "claude-team-usage production env setup"
echo "  target: ${SERVER_HOST_ALIAS}:${REMOTE_ENV}"
echo

read -r -p "DATABASE_URL (Neon Postgres, postgres://... sslmode=require): " DATABASE_URL
read -r -p "ANTHROPIC_ADMIN_API_KEY (sk-ant-admin01-...): " ANTHROPIC_ADMIN_API_KEY
read -r -p "ANTHROPIC_ORG_ID (optional, leave blank to skip): " ANTHROPIC_ORG_ID
read -r -p "AUTH_RESEND_KEY (re_...): " AUTH_RESEND_KEY
read -r -p "EMAIL_FROM (default: instyle group <noreply@instyle.group>): " EMAIL_FROM
EMAIL_FROM="${EMAIL_FROM:-instyle group <noreply@instyle.group>}"

read -r -p "ADMIN_EMAILS (comma-separated, must end with @instyle.group): " ADMIN_EMAILS
read -r -p "JPY_PER_USD (default: 155): " JPY_PER_USD
JPY_PER_USD="${JPY_PER_USD:-155}"

# Auto-generated secrets
AUTH_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
SYNC_TOKEN="$(openssl rand -hex 32)"

tmp="$(mktemp -t claude-team-usage-env.XXXXXX)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# generated by scripts/setup-prod-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "DATABASE_URL=${DATABASE_URL}"
  echo "AUTH_SECRET=${AUTH_SECRET}"
  echo "AUTH_URL=${APP_URL}"
  echo "AUTH_TRUST_HOST=true"
  echo "AUTH_RESEND_KEY=${AUTH_RESEND_KEY}"
  echo "EMAIL_FROM=${EMAIL_FROM}"
  echo "ADMIN_EMAILS=${ADMIN_EMAILS}"
  echo "ANTHROPIC_ADMIN_API_KEY=${ANTHROPIC_ADMIN_API_KEY}"
  [ -n "${ANTHROPIC_ORG_ID}" ] && echo "ANTHROPIC_ORG_ID=${ANTHROPIC_ORG_ID}"
  echo "SYNC_TOKEN=${SYNC_TOKEN}"
  echo "JPY_PER_USD=${JPY_PER_USD}"
} > "$tmp"

bold "installing env on ConoHa (deploy:deploy, mode 600)"
scp -q "$tmp" "${SERVER_HOST_ALIAS}:/tmp/claude-team-usage-env.tmp"
ssh "${SERVER_HOST_ALIAS}" "install -o ${SERVER_USER} -g ${SERVER_USER} -m 600 /tmp/claude-team-usage-env.tmp ${REMOTE_ENV} && rm -f /tmp/claude-team-usage-env.tmp"

bold "done"
echo "  generated AUTH_SECRET (hidden)"
echo "  generated SYNC_TOKEN  (hidden)"
echo "  cron line for ConoHa crontab:"
cat <<EOF

  0 */6 * * * curl -fsS -H "Authorization: Bearer \$SYNC_TOKEN" ${APP_URL}/api/sync?source=all >> /var/log/${CATEGORY}-${APP_NAME}-sync.log 2>&1

EOF
echo "  retrieve SYNC_TOKEN later with:"
echo "    ssh ${SERVER_HOST_ALIAS} 'grep -E ^SYNC_TOKEN= ${REMOTE_ENV}'"
