#!/usr/bin/env bash
# Generate the production .env for claude-team-usage and scp it to the
# ConoHa app env file. Run interactively in iTerm/Terminal — Claude Code's
# `!` bash does not have a TTY and will break on `read -s` prompts.
set -euo pipefail

CATEGORY="app"
APP_NAME="claude-team-usage"
SERVER_USER="deploy"
SERVER_HOST_ALIAS="conoha-deploy" # uses ~/.ssh/config alias
REMOTE_ENV="/var/www/_shared/apps/${CATEGORY}-${APP_NAME}.env"
APP_URL="https://app.instyle.group/${APP_NAME}"
AUTH_BASE_URL="${APP_URL}/api/auth"  # Auth.js v5 は pathname を auth basePath として読む

bold() { printf "\033[1m%s\033[0m\n" "$*"; }

if ! command -v ssh >/dev/null 2>&1; then
  echo "ssh not found" >&2; exit 1
fi
if ! ssh -o BatchMode=yes -o ConnectTimeout=5 "${SERVER_HOST_ALIAS}" 'true' 2>/dev/null; then
  echo "Cannot reach ${SERVER_HOST_ALIAS} via ~/.ssh/config. Configure the alias first." >&2
  exit 1
fi

bold "claude-team-usage production env setup"
echo "  target: ${SERVER_HOST_ALIAS}:${REMOTE_ENV}"
echo

read -r -p "DATABASE_URL (Neon Postgres, postgres://... sslmode=require): " DATABASE_URL
read -r -p "ANTHROPIC_ADMIN_API_KEY (sk-ant-admin01-...): " ANTHROPIC_ADMIN_API_KEY
read -r -p "ANTHROPIC_ORG_ID (optional, leave blank to skip): " ANTHROPIC_ORG_ID

# Vercel の "Reveal value" コピペ等で `KEY=value` 形式の prefix が
# 混入してしまう事故が頻発するので、先頭の <KEY>= を自動で削る。
DATABASE_URL="${DATABASE_URL#DATABASE_URL=}"
ANTHROPIC_ADMIN_API_KEY="${ANTHROPIC_ADMIN_API_KEY#ANTHROPIC_ADMIN_API_KEY=}"
ANTHROPIC_ORG_ID="${ANTHROPIC_ORG_ID#ANTHROPIC_ORG_ID=}"

read -r -s -p "ADMIN_PASSWORD (共通パスワード、画面に表示されません): " ADMIN_PASSWORD
echo
read -r -s -p "ADMIN_PASSWORD (確認のためもう一度): " ADMIN_PASSWORD_CONFIRM
echo
if [ "${ADMIN_PASSWORD}" != "${ADMIN_PASSWORD_CONFIRM}" ]; then
  echo "パスワードが一致しません" >&2; exit 1
fi
if [ ${#ADMIN_PASSWORD} -lt 12 ]; then
  echo "パスワードは 12 文字以上推奨です" >&2; exit 1
fi

read -r -p "JPY_PER_USD (default: 155): " JPY_PER_USD
JPY_PER_USD="${JPY_PER_USD:-155}"

# Auto-generated secrets
AUTH_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
SYNC_TOKEN="$(openssl rand -hex 32)"

# bcrypt hash は single-quote で wrap して書き出すため、`$` のバックスラッシュ
# エスケープは不要（quote 内で literal 扱いになる）。
# 旧仕様では `\$` にエスケープしていたが、新しい qq() の single-quote wrap と
# 二重に効いて hash 中に literal `\$` が混入し、bcrypt.compare が常に false
# になっていた。
ADMIN_PASSWORD_HASH="$(node -e "process.stdout.write(require('bcryptjs').hashSync(process.argv[1], 12))" "${ADMIN_PASSWORD}")"

tmp="$(mktemp -t claude-team-usage-env.XXXXXX)"
trap 'rm -f "$tmp"' EXIT

# 値に & ? 空白などが含まれていても source 時に壊れないよう、
# 全部 single quote で括る。内部の ' は '\'' でエスケープする。
qq() { printf "'%s'" "${1//\'/\'\\\'\'}"; }
{
  echo "# generated by scripts/setup-prod-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "DATABASE_URL=$(qq "${DATABASE_URL}")"
  echo "AUTH_SECRET=$(qq "${AUTH_SECRET}")"
  echo "AUTH_URL=$(qq "${AUTH_BASE_URL}")"
  echo "AUTH_TRUST_HOST=true"
  echo "ADMIN_PASSWORD_HASH=$(qq "${ADMIN_PASSWORD_HASH}")"
  echo "ANTHROPIC_ADMIN_API_KEY=$(qq "${ANTHROPIC_ADMIN_API_KEY}")"
  [ -n "${ANTHROPIC_ORG_ID}" ] && echo "ANTHROPIC_ORG_ID=$(qq "${ANTHROPIC_ORG_ID}")"
  echo "SYNC_TOKEN=$(qq "${SYNC_TOKEN}")"
  echo "JPY_PER_USD=$(qq "${JPY_PER_USD}")"
} > "$tmp"

bold "installing env on ConoHa (deploy:deploy, mode 600)"
scp -q "$tmp" "${SERVER_HOST_ALIAS}:/tmp/claude-team-usage-env.tmp"
ssh "${SERVER_HOST_ALIAS}" "install -o ${SERVER_USER} -g ${SERVER_USER} -m 600 /tmp/claude-team-usage-env.tmp ${REMOTE_ENV} && rm -f /tmp/claude-team-usage-env.tmp"

bold "done"
echo "  generated AUTH_SECRET (hidden)"
echo "  generated SYNC_TOKEN  (hidden)"
echo "  generated ADMIN_PASSWORD_HASH (hidden, \$ escaped for dotenv safety)"
echo
echo "  --- crontab 行（env を都度 source して \$SYNC_TOKEN を展開する形）---"
cat <<EOF

  0 */6 * * * bash -lc 'set -a; . ${REMOTE_ENV}; set +a; curl -fsS -H "Authorization: Bearer \$SYNC_TOKEN" ${APP_URL}/api/sync?source=all' >> /var/log/${CATEGORY}-${APP_NAME}-sync.log 2>&1

EOF
echo "  ssh conoha-deploy 'crontab -e' で上記行を追加（インデント無しで）"
echo
echo "  値の存在だけ確認したい場合（中身は出さない）:"
echo "    ssh ${SERVER_HOST_ALIAS} 'grep -c ^SYNC_TOKEN= ${REMOTE_ENV}'  # → 1 なら OK"
echo "    ssh ${SERVER_HOST_ALIAS} 'grep -c ^ADMIN_PASSWORD_HASH= ${REMOTE_ENV}'  # → 1 なら OK"
